In [1]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the no. of dimensions of a tensor (ndim stands for no. of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [24]:
# Create a matric (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [12]:
# Create another matrix
matrix2 = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype = tf.float16)
# specify the data type with dtype parameter
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [23]:
# whats the no.of dimensions of matrix 2?
matrix2.ndim
# Notice the pattern of ndim? it only sees the number of elements in shape

2

In [14]:
# LET'S CREATE A TENSOR
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,171,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 13,  14,  15],
        [ 16, 171,   8]]], dtype=int32)>

In [15]:
tensor.ndim

3

**What we've created so far:**

*  scalar: a single number
*  vector: a no. with directon
*  matrix: a 2-D array of numbers
*  tensor: an n-D array of no.s (**when n can be any number, a 0-D tensor is scalar, a 1-D tensor is a vector**)





### Creating tensors with `tf.variable`

In [18]:
# Creating same tensor with tf.variable() as above
changing_tensor = tf.Variable([10,7])
unchange_tensor = tf.constant([10,7])
changing_tensor , unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [22]:
# Let's try to change one of the elements in changeable tensor
changing_tensor[0].assign(7)
changing_tensor
# We can't change unchangeable tensor because it's defined as constant

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors
Random tensor are tensors of some arbitrary size which contain random numbers.

In [27]:
# Create two Random (but the same) tensors
r1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
r1 = r1.normal(shape=(3,2))
r2 = tf.random.Generator.from_seed(42)
r2 = r2.normal(shape=(3,2))

# Are they equal?
r1,r2,r1==r2
# they are pseudo-random numbers based on seed(). since both no.s inside seed() is same,
# both are equal

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a Tensor

In [30]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [31]:
not_shuffled.ndim

2

In [36]:
#shuffle our non shuffled tensor

#tf.random.set_seed(42)
#if the above stmt is added and you run the code, then op is constant as what you defined first

tf.random.shuffle(not_shuffled,seed=42)
#changes everytime you run it

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make Tensors

In [39]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [40]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main diff btwn NumPy arrays and TnesorFlow tensors is that tensors can be run on a GPU computing

In [42]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital variable for matrix or tensor
# y = tf.constant(vector) #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [45]:
A = tf.constant(numpy_A,shape=(2,3,4))
# 2*3*4 = 24. if instead of 4 we gave 5, it will show error. 3*8 will also work
# since total is 25
B = tf.constant(numpy_A)
A, B
# Now A is in a form of tensor!!!

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [46]:
A.ndim

3

# Getting Information from Tensors

when dealing with tesors, you want to be aware of the following attribute:
* Shape
* Rank
* Axis or Dimension
* Size





In [48]:
# Create a rank 4 tensor (4-D)
r4_tensor = tf.zeros(shape=[2,3,4,5])
r4_tensor
# 2,3,4,5 - 2 groups of matrices, which has 3 arrays each with 4 rows and 5 columns in op

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [51]:
r4_tensor.shape, r4_tensor.ndim, tf.size(r4_tensor)
# numpy in op is 120 = 2*3*4*5

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [54]:
# Get various attributes of our tensor
print("Datatype of every element: ",r4_tensor.dtype)
print("Number of dimensions (rank): ",r4_tensor.ndim)
print("Shape of tensor: ",r4_tensor.shape)
print("Elements along 0 axis: ",r4_tensor.shape[0])
print("Elements along the last axis: ",r4_tensor.shape[-1])
print("\n")
print("Total number of elements in our tensor: ",tf.size(r4_tensor))
print("Total number of elements in our tensor: ",tf.size(r4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along the last axis:  5


Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


# Indexing Tensors (similar to python lists)

In [57]:
r4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [60]:
#Get the first element from each dimension from each index except for the final one
r4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [63]:
# Create a rank 2 tensor (2D)
r2_tensor = tf.constant([[10,7],[3,4]])
r2_tensor.shape, r2_tensor.ndim

(TensorShape([2, 2]), 2)

In [64]:
# Get the last item of each row of our rank 2 tensor
r2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [65]:
# Add extra dimension to our rank 2 tensor
r3_tensor = r2_tensor[...,tf.newaxis]
# ... also means :,:,tf.newaxis
r3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [67]:
# Alternative to tf.newaxis
tf.expand_dims(r2_tensor,axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [68]:
# Expand 0 axis
tf.expand_dims(r2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>