# Manipulating tensors (Tensor operations)
**Basic operations**

`+`,`-`,`*`,`/`

In [1]:
import tensorflow as tf

In [2]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [3]:
# original tensor is unchanged though
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [4]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [5]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [6]:
# We can use the tensorflow built-in functions too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix Multiplication (most common tensor operation)

There are two rules our tensors (or matrices) need to fulfill if we're going to matric multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of outer dimensions.

`if matrix 1 is 3x3 and matrix 2 is 3x2, the inner number 3 & 3 matches. so rule 1 satisfied. The resultant matrix will be 3x2 matrix and rule 2 is satisfied`

**The dot product**

Matrix multiplication is also referred to as the dot product
you can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `A @ B`









In [7]:
# Matrix Multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [8]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [9]:
# Create a (3,2) tensor
X = tf.constant([[1,2,3],[3,4,5]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [10]:
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [112, 124]], dtype=int32)>

In [11]:
# Can do with transpose
X, tf.transpose(X),tf.reshape(X, shape=(2,3))
# Notice difference between reshape and transpose

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4],
        [3, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5]], dtype=int32)>)

# Changing the datatype of a tensor

In [12]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [13]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

# Aggregating tensors
Condensing them from multiple values down to a smaller amount of values

In [14]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [15]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [16]:
import numpy as np
# Create a random tensor with values btwn 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74,  6, 86,  1, 18,  6, 80, 61,  9, 39, 39, 93, 64, 67, 39,  5, 99,
       37,  6, 13, 99, 54, 34, 31, 14, 23, 36,  8, 62, 98, 94, 34, 29, 29,
       99, 61, 57, 45, 37, 96, 52, 76, 79, 11, 34, 84, 23, 51, 78, 57])>

In [17]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [18]:
# 1. Find the minimum
# 2. Find the maximum
# 3. Find mean
# 4. Find sum
print("Minimum: ",tf.reduce_min(E)),print("Maximum: ",tf.reduce_max(E)),print("Mean: ",tf.reduce_mean(E)),print("Sum: ",tf.reduce_sum(E))

Minimum:  tf.Tensor(1, shape=(), dtype=int64)
Maximum:  tf.Tensor(99, shape=(), dtype=int64)
Mean:  tf.Tensor(48, shape=(), dtype=int64)
Sum:  tf.Tensor(2427, shape=(), dtype=int64)


(None, None, None, None)

In [19]:
import tensorflow_probability as tfp
# Find the variance of our tensor
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=916>

In [20]:
# Find the standard deviation of tensor
p = tf.cast(E, dtype=tf.float32) # int to float for std dev
tf.math.reduce_std(p)

<tf.Tensor: shape=(), dtype=float32, numpy=30.26563>

In [23]:
# Find the variance of tensor E
tf.math.reduce_variance(p)
# This shows that tensorflow probability is not needed as we did above
# Can be done like std dev using math function

<tf.Tensor: shape=(), dtype=float32, numpy=916.0084>

# Find the positional maximum and minimum

In [25]:
# Create a new tensor for finding the above
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [26]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [27]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [28]:
# Find the max value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [29]:
# Positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [31]:
tf.reduce_min(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

# Squeezing a tensor (removing all single dimensions)

In [32]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [33]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [34]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-hot encoding tensors

In [35]:
# Create a list of indices
l1 = [0,1,2,3] #could be red,green,purple,blue

#one-hot encode our list of indices
tf.one_hot(l1,depth=4) #depth should be equal to no. elements in the list

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [38]:
# Specify custom values for one hot encoding
tf.one_hot(l1,depth=4,on_value="I am sick",off_value="I am playing")
# on_value = 1

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I am sick', b'I am playing', b'I am playing', b'I am playing'],
       [b'I am playing', b'I am sick', b'I am playing', b'I am playing'],
       [b'I am playing', b'I am playing', b'I am sick', b'I am playing'],
       [b'I am playing', b'I am playing', b'I am playing', b'I am sick']],
      dtype=object)>

# Squaring, log, square root

In [39]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [40]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [44]:
# For finding sqrt, method requires non-int type. so we have to convert to float
p = tf.cast(H,dtype = tf.float32)
tf.sqrt(p)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [45]:
# Log
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and NumPy
Tensorflow interacts beautifully with NumPy arrays.

In [46]:
# Create a tensor directly from NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [49]:
# Convert our tensor back to NumPy  (2 types - np. and J.)
np.array(J),type(np.array(J)),print("\n"),J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]),
 numpy.ndarray,
 None,
 array([ 3.,  7., 10.]),
 numpy.ndarray)

In [50]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [52]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding Access to GPUs

In [2]:
# Go to Runtime -> Chnage runtime type -> choose GPU and run this
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Mon Oct  2 17:10:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#**NOTE:** if u have access to a CUDA-enabled GPU, TensorFlow will automatically use it wherever possible


